-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.4.2
    hooks:
      -   id: autopep8-wrapper
          args: ['-i']
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
      -   id: check-case-conflict
      -   id: check-merge-conflict
