sudo: required
language: python
# Keep up to date with the tox.ini list
env:
  - TOXENV=py34
  - TOXENV=pypy3
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - make test
after_success:
  - coveralls
